### ISSUE TITLE
textshaping install error on linux RHEL 7.4 - hb-ft.h: No such file or directory

### ISSUE THREAD

**Issue by MikeDMorgan** [r-lib/textshaping#21]
I am currently unable to install `textshaping` (as a dependency for other packages) on RHEL 7.4 (without root):

```
> install.packages("textshaping")
trying URL 'https://cran.ma.imperial.ac.uk/src/contrib/textshaping_0.3.5.tar.gz'
Content type 'application/x-gzip' length 35623 bytes (34 KB)
==================================================
downloaded 34 KB

* installing *source* package ‘textshaping’ ...
** package ‘textshaping’ successfully unpacked and MD5 sums checked
** using staged installation
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-L/homes/mdmorgan/local/lib -lharfbuzz -lfreetype -lfribidi  
--------------------------- [ANTICONF] --------------------------------
Configuration failed to find the harfbuzz freetype2 fribidi library. Try installing:
 * deb: libharfbuzz-dev libfribidi-dev (Debian, Ubuntu, etc)
 * rpm: harfbuzz-devel fribidi-devel (Fedora, EPEL)
 * csw: libharfbuzz_dev libfribidi_dev (Solaris)
 * brew: harfbuzz fribidi (OSX)
If harfbuzz freetype2 fribidi is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a harfbuzz freetype2 fribidi.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: hb-ft.h: No such file or directory
compilation terminated.
--------------------------------------------------------------------
ERROR: configuration failed for package ‘textshaping’
* removing ‘/homes/mdmorgan/lib64/R/library/textshaping’

The downloaded source packages are in
	‘/scratch/RtmpUJO03e/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("textshaping") :
  installation of package ‘textshaping’ had non-zero exit status
```

I have local versions of all 3 libraries installed (they are absent on our server). My `$PKG_CONFIG_PATH` is set to find them, such that `pkg-config` can identify all 3 libraries:

```
$ pkg-config harfbuzz --libs
-L/homes/mdmorgan/local/lib -lharfbuzz  
$ pkg-config freetype2 --libs
-L/homes/mdmorgan/local/lib -lfreetype  
$ pkg-config fribidi --libs
-L/homes/mdmorgan/local/lib -lfribidi 
```

I am somewhat at a loss as to why `textshaping` still fails to identify nh-ft.h, which I can confirm is present:

```
$ ll local/include/harfbuzz/ | grep hb-ft
-rw-r--r-- 1 mdmorgan marioni  4146 Jul 16 10:42 hb-ft.h
```

The same error arises when trying to install textshaping from source with R CMD install with the paths configured:

```
$ R CMD INSTALL --configure-vars='INCLUDE=/homes/mdmorgan/local/include/ LIB_DIR=/homes/mdmorgan/local/lib/' textshaping_0.3.5.tar.gz 
* installing to library ‘/homes/mdmorgan/lib64/R/library’
* installing *source* package ‘textshaping’ ...
** package ‘textshaping’ successfully unpacked and MD5 sums checked
** using staged installation
Found INCLUDE_DIR and/or LIB_DIR!
Using PKG_CFLAGS=-I 
Using PKG_LIBS=-L/homes/mdmorgan/local/lib/ -lfreetype -lharfbuzz -lfribidi -lpng
--------------------------- [ANTICONF] --------------------------------
Configuration failed to find the harfbuzz freetype2 fribidi library. Try installing:
 * deb: libharfbuzz-dev libfribidi-dev (Debian, Ubuntu, etc)
 * rpm: harfbuzz-devel fribidi-devel (Fedora, EPEL)
 * csw: libharfbuzz_dev libfribidi_dev (Solaris)
 * brew: harfbuzz fribidi (OSX)
If harfbuzz freetype2 fribidi is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a harfbuzz freetype2 fribidi.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: hb-ft.h: No such file or directory
compilation terminated.
--------------------------------------------------------------------
ERROR: configuration failed for package ‘textshaping’
* removing ‘/homes/mdmorgan/lib64/R/library/textshaping’
```

R Session info:
```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS:   /homes/mdmorgan/lib64/R/lib/libRblas.so
LAPACK: /homes/mdmorgan/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.2 tools_4.0.2 
```

**Comment by mdancho84** [comment]
Hey, I ran into this too when compiling a docker image that depends on `textshaping`. The solution for me was to add the following linux dependencies (running on debian):

```
libharfbuzz-dev  libfribidi-dev
```

I noticed it in the error message here. 

![image](https://user-images.githubusercontent.com/13734662/152693570-30195c3b-77e7-4d7a-a409-786d14c7a6bf.png)

**Comment by sanjmeh** [comment]
Hi guys

Was there a solution found? 

I am also stuck at the same point and @mdancho84 your suggested path `libharfbuzz-dev  libfribidi-dev` on ubuntu 20 does not work either (command does not exist).

I landed up installing `ragg` as suggested on this Rstudio blog https://www.rstudio.com/blog/rstudio-v1-4-preview-little-things/ which in turn wants `textshaping` and then it goes into a snowball of errors.

**Comment by pkinif** [comment]
Hi @sanjmeh,

I have deployed an R Shiny application on ubuntu 22.04.

**Comment by chagas98** [comment]
@mdancho84 it worked like a charm here for textshaping install. I ran in terminal: `sudo apt-get install libharfbuzz-dev  libfribidi-dev`

I had problems with R `devtools` package and textshaping was one of the issues.

**Comment by sanjmeh** [comment]
Noted. Thanks.

**Comment by amarinderthind** [comment]
This Worked for me ...

> Hey, I ran into this too when compiling a docker image that depends on `textshaping`. The solution for me was to add the following linux dependencies (running on debian):
> 
> ```
> libharfbuzz-dev  libfribidi-dev
> ```
> 
> I noticed it in the error message here.
> 
> ![image](https://user-images.githubusercontent.com/13734662/152693570-30195c3b-77e7-4d7a-a409-786d14c7a6bf.png)

**Comment by thomasp85** [comment]
@lijxug it's hard to say - I don't know your particular issue because you haven't shared it here. For the other people here installing the correct system dependencies seems to have solved their issues

**Comment by lizhan96** [comment]
i've got the sample error, I can't find any solutions in the internet.

**Comment by Ezibenroc** [comment]
On my system (WSL2 with Ubuntu 20), installing the two mentioned packages was not enough, I also had to install `libfontconfig1-dev`.

So in the end, this solved my problem:
```sh
sudo apt-get install libharfbuzz-dev libfribidi-dev libfontconfig1-dev
```

**Comment by cleivama** [comment]
> Hi @sanjmeh,
> 
> I have deployed an R Shiny application on ubuntu 22.04. Here are the Linux dependencies I had to add in my dockerfile to install textshaping in my docker image.
> 
> ```
> libharfbuzz-dev \ 
> libfribidi-dev \
> libfreetype6-dev \
> libpng-dev \
> libtiff5-dev \
> libjpeg-dev \
> ```

This solved my issue, I was missing libtiff5-dev. Thanks!

**Comment by orbello** [comment]
I had a similar problem. The problem was that the "include" subdirectories of fribidi, harfbuzz, and freetype2 were not terminal directories. Each of the include subdirectories had "fribidi", "harfbuzz", and "freetype2" subdirectories, respectively, which contain the needed files (so, they should be the terminal directories of any environment variable hitherto terminating in "include" dir). So, you don't actually need the dev versions. As for libtiff, lippng, and libjpeg libraries, the "include" subdirectories are terminal, so everything is fine with them.

**Comment by ag-abhishek** [comment]
> On my system (WSL2 with Ubuntu 20), installing the two mentioned packages was not enough, I also had to install `libfontconfig1-dev`.
> 
> So in the end, this solved my problem:
> 
> ```shell
> sudo apt-get install libharfbuzz-dev libfribidi-dev libfontconfig1-dev
> ```
this solved my problem

**Comment by MarioCazalla** [comment]
Hi all, 
I had this issue too. But I have installed this libraries and works for me (sudo apt install Library):
libharfbuzz-dev \ 
libfribidi-dev \
libfreetype6-dev \
libpng-dev \
libtiff5-dev \
libjpeg-dev \

**Comment by KatChampion** [comment]
I am getting a similar error. But I am running R Studio server and I don't have sudo access. So I can't install the dependancies directly. Is there another way around this issue?
Also this came up when I was reinstalling tidyverse but previously I was able to install and run tidyverse so I don't know what changed that causes textshaping to fail.

**Comment by imanojkumar** [comment]
on RHEL 8:

`**yum install harfbuzz-devel fribidi-devel**`

**Comment by quattro** [comment]
I needed to add glib and graphite2 to my CPATH to get installation to work.

**Comment by lmeserve** [comment]
I am on a Apple M1 computer. The error message suggests:

`brew install harfbuzz fribidi`

This solved this issue for me.

**Comment by ZhangDengwei** [comment]
I suggest a solution for this issue, as I installed R using `conda` without host privilege, I can install `textshaping` using `conda`,

```
conda install -c conda-forge r-textshaping
```

**Comment by jxu** [comment]
I'm on an old RHEL 7.9 server. I did find harfbuzz.pc, fribidi.pc, and freetype2.pc in some anaconda lib directory using `locate`. 

```
export PKG_CONFIG_PATH=/sasdata/anaconda3/lib/pkgconfig
R CMD INSTALL /tmp/RtmpecGmiD/downloaded_packages/textshaping_0.3.7.tar.gz
```
I've had issues with this library on Ubuntu too, but on that machine I had a working apt.

**Comment by nextmarte** [comment]
> libharfbuzz-dev \ 
> libfribidi-dev \
> libfreetype6-dev \
> libpng-dev \
> libtiff5-dev \
> libjpeg-dev \

it worketd for me!! thx!!
