### ISSUE TITLE
{ragg} crashes if the font doesn't contain the unicode character

### ISSUE THREAD

**Issue by amirmasoudabdol** [r-lib/textshaping#23]
We, at JASP, ran into this [issue](https://github.com/jasp-stats/INTERNAL-jasp/issues/1540) where `ragg` crashes if our dataset contains a specific character which is not supported by the font. This is a common issues I guess, but I was hopping that we get a placeholder instead of full on crash. I'm wondering if anyone has experienced something like this, and if there is any workaround for it.

The following example only works with a handful of fonts, Arial, Times, and Tahoma. The culprit is this  Ӻ, [Cyrillic Capital (and Small) Letter Ghe with stroke and hook](https://en.wikipedia.org/wiki/List_of_Unicode_characters) character which is not supported by many fonts. If you remove this character, then the plot will be generated with no issue. 

```r
# Removing the Ӻ from the string
# dd[30, "unicode"] <- "₢_Ἁ__ט_ሜ_ழ_क़_ᚽ_ㄸ"
# dd[31, "unicode"] <- "₣_ἅ__טּ_ም_ள_ख_ᚾ_ﾨ"

plt <- ggplot2::ggplot(dd, ggplot2::aes(x = unicode)) +
  ggplot2::geom_histogram(stat = "count")

plot(plt)

ragg::agg_png("plotje.png")
plot(plt)
dev.off()
```

Is there a way to stop `ragg` from crashing the R session, or patch it such that it returns a placeholder instead of the missing character?

[debug.csv](https://github.com/r-lib/ragg/files/7129323/debug.csv)

**Comment by amirmasoudabdol** [comment]
What is the fallback font on macOS? If it falls back to any of the San Francisco fonts, they are not necessary behaving when it comes to third-party use.

**Comment by thomasp85** [comment]
It tries SFCompact.ttf

**Comment by thomasp85** [comment]
So that is probably the source of the issue

**Comment by thomasp85** [comment]
It seems macOS is reporting the fallback to be SFCompact.ttf at index 16, but since it is a ttf file it cannot contain multiple fonts which means the index is nonsensical... This is all probably because we are messing with system level stuff we shouldn't

**Comment by amirmasoudabdol** [comment]
I think so too. Apple is being very difficult with these fonts. They are everywhere, and they want you to them, but not everywhere! I think the best option is to probably fix the fallback to the Ariel or Times if possible. I scanned my fonts library and there are very few fonts that support this specific character, and I assume if they have this one, they should have most other characters too.

**Comment by thomasp85** [comment]
yeah... I'll ponder on that. I don't particularly like hardcoding stuff like that in. At least I'll fix it so it doesn't crash
