### ISSUE TITLE
Retrieving glyphs with `shape_text()`

### ISSUE THREAD

**Issue by teunbrand** [r-lib/textshaping#28]
Hello Thomas and team,

Summarising the issue below: it would be wonderful if the `shape_text()` function could return unicode glyphs or codepoints.

I think the `shape_text()` function is great for its support for BiDi text and character composition, so thank you so much for bringing the Harfbuzz and Fridibi libraries to the R ecosystem! It has been very helpful for a ggplot2 extension we've been working on.

Currently, the `shape_text()` function does not return the glyphs as code points or unicode, but does helpfully return an index to the font file. Using a workaround, we can use `systemfonts::glyph_info()` to query all indices of a font and reconstruct from there. This works if the font supports the glyphs that we want, but does not work in all cases because we cannot enjoy font fallback in this way.

``` r
library(textshaping)

# Example Japanese text taken from here: https://www.tidyverse.org/blog/2021/02/modern-text-features/#font-fallback
x <- shape_text("Test \u3053\u306e\u65E5\u672C\u8A9E\u3067\u3059", family = "Arial")

# Querying most of unicode space
glyphs <- systemfonts::glyph_info(
  intToUtf8(1:64000, multiple = TRUE), family = "Arial"
)

# Translating font indices back to glyphs
i <- match(x$shape$index, glyphs$index)
do.call(paste0, list(glyphs$glyph[i], collapse = ""))
#> [1] "Test \001\001\001\001\001\001\001"
```

<sup>Created on 2021-12-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

We have tried various other methods such as `strsplit()`'ing the `metrics$string` output, but this becomes hairy when the string contains compound characters. Even using `stringi::stri_split_boundaries(..., type = "character")` does not always return the same lengths of strings as there are rows in the `shape` output.

So my question is this: what is a reliable method to retrieve (clusters of) glyphs parallel to the rows of the `shape` output? If there isn't any, please feel free to consider this issue a feature request instead.

Thanks for reading!

**Comment by thomasp85** [comment]
There is unfortunately no way to do this. There is no requirement for a ligature to coincide with a unicode glyph - it can be anything the font developer wants. Because of this there is also no way to link whatever the font substitutes in with a generalised description of it which is why I omitted it in the first place
