### ISSUE TITLE
Installation   error 

### ISSUE THREAD

**Issue by Kiran936** [r-lib/textshaping#30]
installation of package ‘textshaping’ had non-zero exit status

I am using Ubutu 20 
R 4.1.2

How to install this

**Comment by thomasp85** [comment]
My guess is that you don't have the required system libraries installed, but without the installation log it is impossible to say

**Comment by Kiran936** [comment]
i could solve it,,, there are so many lib associated with it,, some need to be installed through Linux terminal while other with Rstudio, thanks

**Comment by ltuijnder** [comment]
I also had an error message. But I would say the message printed under the `ANTICONF` header was pretty clear to me. For that was:
```
--------------------------- [ANTICONF] --------------------------------
Configuration failed to find the harfbuzz freetype2 fribidi library. Try installing:
 * deb: libharfbuzz-dev libfribidi-dev (Debian, Ubuntu, etc)
 * rpm: harfbuzz-devel fribidi-devel (Fedora, EPEL)
 * csw: libharfbuzz_dev libfribidi_dev (Solaris)
 * brew: harfbuzz fribidi (OSX)
If harfbuzz freetype2 fribidi is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a harfbuzz freetype2 fribidi.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
```
