### ISSUE TITLE
error in install.packages('textshaping')：fatal error: hb-ft.h: No such file or directory

### ISSUE THREAD

**Issue by lizhan96** [r-lib/textshaping#31]
`install.packages('textshaping')`
```
* installing *source* package ‘textshaping’ ...
** package ‘textshaping’ successfully unpacked and MD5 sums checked
** using staged installation
Package fribidi was not found in the pkg-config search path.
Perhaps you should add the directory containing `fribidi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fribidi' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lfreetype -lharfbuzz -lfribidi -lpng
--------------------------- [ANTICONF] --------------------------------
Configuration failed to find the harfbuzz freetype2 fribidi library. Try installing:
 * deb: libharfbuzz-dev libfribidi-dev (Debian, Ubuntu, etc)
 * rpm: harfbuzz-devel fribidi-devel (Fedora, EPEL)
 * csw: libharfbuzz_dev libfribidi_dev (Solaris)
 * brew: harfbuzz fribidi (OSX)
If harfbuzz freetype2 fribidi is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a harfbuzz freetype2 fribidi.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: hb-ft.h: No such file or directory
compilation terminated.
--------------------------------------------------------------------
ERROR: configuration failed for package ‘textshaping’
* removing ‘/usr/local/lib/R/site-library/textshaping’
Warning in install.packages :
  installation of package ‘textshaping’ had non-zero exit status
```

harfbuzz freetype2 fribidi is already installed and add into the .bashrc
`locate harfbuzz.pc freetype2.pc fribidi.pc`
```
/home/lizhan/anaconda3/lib/pkgconfig/freetype2.pc
/home/lizhan/anaconda3/lib/pkgconfig/fribidi.pc
/home/lizhan/anaconda3/lib/pkgconfig/harfbuzz.pc
```

`export PKG_CONFIG_PATH=/data_6t/lizhan/02.software/libgtextutils-0.7/lib/pkgconfig:$PKG_CONFIG_PATH:/home/lizhan/anaconda3/bin/:/home/lizhan/anaconda3/lib/pkgconfig/:/usr/lib/x86_64-linux-gnu/pkgconfig/:/home/lizhan/anaconda3/include/harfbuzz/`

**Comment by thomasp85** [comment]
What do you get if you run
```
pkg-config harfbuzz fribidi --cflags
```
and
```
pkg-config harfbuzz fribidi --libs
```
?

**Comment by lizhan96** [comment]
> 如果你跑步，你会得到什么
> 
> ```
> pkg-config harfbuzz fribidi --cflags
> ```
> 
> 和
> 
> ```
> pkg-config harfbuzz fribidi --libs
> ```
> 
> ?

`$pkg-config harfbuzz fribidi --cflags
-I/home/lizhan/anaconda3/include/harfbuzz -I/home/lizhan/anaconda3/include/freetype2 -I/home/lizhan/anaconda3/include/libpng16 -I/home/lizhan/anaconda3/include -I/home/lizhan/anaconda3/include/glib-2.0 -I/home/lizhan/anaconda3/lib/glib-2.0/include -I/home/lizhan/anaconda3/include -I/home/lizhan/anaconda3/include/fribidi
`
`$pkg-config harfbuzz fribidi --libs
-L/home/lizhan/anaconda3/lib -L/home/lizhan/anaconda3/lib64 -lharfbuzz -lfribidi
`

I got such infomation.

**Comment by thomasp85** [comment]
Is your R installation through conda?

**Comment by lizhan96** [comment]
> Is your R installation through conda?

no, I think.

**Comment by thomasp85** [comment]
hmm... ok... but your system libraries seems to be installed through a conda environment based on the paths... @jeroen do you have any good idea as to how to proceed?

**Comment by lizhan96** [comment]
> hmm... ok... but your system libraries seems to be installed through a conda environment based on the paths... @jeroen do you have any good idea as to how to proceed?

harfbuzz, freetype2, fribidii was installed by the command `apt install`

**Comment by jeroen** [comment]
Your are definitly mixing anaconda libs with apt libs. What do you get in R for

```
R.home()
```

> harfbuzz, freetype2, fribidii was installed by the command apt install

Then don't add those `/home/lizhan/anaconda3/......` paths to your `PKG_CONFIG_PATH`

**Comment by jeroen** [comment]
If you are using anaconda R, you can install the package from here: https://anaconda.org/conda-forge/r-textshaping

**Comment by lizhan96** [comment]
> 

> R.home()
[1] "/usr/lib/R"

**Comment by mintzj** [comment]
I encountered this error when installing textshaping, and was able to resolve it by installing libfribidi-dev.  I had libharfbuzz-dev and libfribidi but not the dev version of libfribidi. 

On a side note, this error halts the installation of devtools, due to a devtools dependency on textshaping.

**Comment by lizhan96** [comment]
Thanks for your advises.

**Comment by marshals1999** [comment]
you can use the command line as: sudo apt install  libharfbuzz-dev libfribidi-dev to install the packages, and then install the R package again. have a try.

**Comment by akshaytuptewar19** [comment]
How to install  libharfbuzz-dev, libfribidi-dev  packages for windows?

> you can use the command line as: sudo apt install libharfbuzz-dev libfribidi-dev to install the packages, and then install the R package again. have a try.

**Comment by akshaytuptewar19** [comment]
> I encountered this error when installing textshaping, and was able to resolve it by installing libfribidi-dev. I had libharfbuzz-dev and libfribidi but not the dev version of libfribidi.
> 
> On a side note, this error halts the installation of devtools, due to a devtools dependency on textshaping.

How to install libharfbuzz-dev, libfribidi-dev packages for windows?

**Comment by opplatek** [comment]
> you can use the command line as: `sudo apt install libharfbuzz-dev libfribidi-dev` to install the packages, and then install the R package again. have a try.

I had to add `libtiff5-dev` to the command (Ubuntu 22.04 LTS). Then it installed ok. The final cmd was `sudo apt install libharfbuzz-dev libfribidi-dev libtiff5-dev`. On older Ubuntu releases, it might be `libtiff4-dev`.

**Comment by thomasp85** [comment]
@lgn-almeida I think the general recommendation is to not mix environments when installing packages. It all works fine if you go all in on conda (even with renv), and it all works fine if you install from CRAN and manage system libraries with brew.

I must admit I believe conda to be a 100% unnecessary complication when it comes to R, but regardless, as long as you use it for everything it should work

**Comment by thomasp85** [comment]
My preferred setup is to use rig to manage multiple r installations, homebrew (assuming you are on macOS) to manage system libraries, and then install packages from CRAN as normal. This is the setup that is less likely to bite you.

**Comment by lgn-almeida** [comment]
Thanks, Thomas. I was previously on a Windows machine and started working on Linux recently, and half of the time I will be on an HPC cluster, so I will check what could be an alternative to homebrew for me. I might go the "apt" route and simply use rig to manage my R installation. Again, thanks for your help, I appreciate it!
