### ISSUE TITLE
Unable to install textshaping package in Debian 8

### ISSUE THREAD

**Issue by mTab86** [r-lib/textshaping#33]
I need textshaping package to install tidyverse, but unable to install. I tried textshaping==0.1.0 also but getting the same error.

`Installing package into ‘/home/alamm/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/textshaping_0.3.6.tar.gz'
Content type 'application/x-gzip' length 35722 bytes (34 KB)
==================================================
downloaded 34 KB

* installing *source* package ‘textshaping’ ...
** package ‘textshaping’ successfully unpacked and MD5 sums checked
** using staged installation
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/fribidi 
Using PKG_LIBS=-lharfbuzz -lfreetype -lfribidi 
** libs
rm -f textshaping.so cpp11.o face_feature.o hb_shaper.o init.o string_bidi.o string_metrics.o string_shape.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG -DNDEBUG -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/fribidi  -I'/usr/local/lib/R/site-library/cpp11/include' -I'/usr/local/lib/R/site-library/systemfonts/include' -I/usr/local/include   -fpic  -g -O2  -c cpp11.cpp -o cpp11.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG -DNDEBUG -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/fribidi  -I'/usr/local/lib/R/site-library/cpp11/include' -I'/usr/local/lib/R/site-library/systemfonts/include' -I/usr/local/include   -fpic  -g -O2  -c face_feature.cpp -o face_feature.o
face_feature.cpp: In function ‘cpp11::writable::list get_face_features_c(cpp11::strings, cpp11::integers)’:
face_feature.cpp:46:59: error: ‘hb_ft_face_create_referenced’ was not declared in this scope
     hb_face_t *face = hb_ft_face_create_referenced(ft_face);
                                                           ^
/usr/local/lib/R/etc/Makeconf:176: recipe for target 'face_feature.o' failed
make: *** [face_feature.o] Error 1
ERROR: compilation failed for package ‘textshaping’
* removing ‘/home/alamm/R/x86_64-pc-linux-gnu-library/4.0/textshaping’
Warning in install.packages :
  installation of package ‘textshaping’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpI65fcF/downloaded_packages’`

**Comment by thomasp85** [comment]
You might have harfbuzz installed without freetype support

Try installing or reinstalling freetype and then reinstalling harfbuzz
