### ISSUE TITLE
Newlines `\n` are ignored

### ISSUE THREAD

**Issue by teunbrand** [r-lib/textshaping#45]
Hi Thomas,

This is a reprex for what we discussed off-github. Essentially, whenever a newline is invoked, it appears as if it is ignored. In the example below, there should be 3 unique `y_offset` values because there are 3 lines separated by newlines.

``` r
library(textshaping)

string <- "This is a long string\nLook; It spans multiple lines\nand all"

txt <- shape_text(string)
unique(txt$shape$y_offset)
#> [1] 2.546875
```

<sup>Created on 2024-06-18 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by AllanCameron** [comment]
Thanks @teunbrand - I was just about to post the same report!
